<?php
if(!defined('TF_CACHE_FW')){
    define('TF_CACHE_FW','C:\xampp\htdocs\Ketsahalo/wp-content/themes/themify-ultra/themify\cache/');
}
if(!defined('TF_CACHE_TIME')){
    define('TF_CACHE_TIME','10080');
}
if(!defined('TF_CACHE_RULES')){
    define('TF_CACHE_RULES','');
}
if(!defined('TF_CACHE_IGNORE')){
    define('TF_CACHE_IGNORE','is_single,is_page,is_front_page,is_home,is_archives,is_tags,is_category,is_feed,is_author');
}